# -*- coding: utf-8 -*-
"""Task 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J7qC_RzY5skGvvU_LNMg19W_t7yuF00N
"""

my_list = [1,2,3,4,5]
my_list.append(6)
my_list.remove(3)
my_list[0] = 10
print(my_list)

my_dict = {'name':'John', 'age':'25','city':'Delhi'}
my_dict['gender'] = 'Female'
del my_dict['age']
my_dict['name'] = 'Jane'
print(my_dict)

my_set = {1,2,3,4,5}
my_set.add(6)
my_set.remove(3)
my_set.discard(1)
my_set.add(44)
print(my_set)